---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    #- name: almalinux
    #image: almalinux:latest
    #pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
